// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClEgWa0UOlv1uLdavhvJnBDNq7z3Nmfck',
    appId: '1:647815433136:web:b819a296dc45123ed96475',
    messagingSenderId: '647815433136',
    projectId: 'new-vetmobile-app',
    authDomain: 'new-vetmobile-app.firebaseapp.com',
    storageBucket: 'new-vetmobile-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNrbyIlnk0D_qKC_l6S68Hd_kXCaXw8PQ',
    appId: '1:647815433136:android:a2d9dc7e679bcdcfd96475',
    messagingSenderId: '647815433136',
    projectId: 'new-vetmobile-app',
    storageBucket: 'new-vetmobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqZIEh3kQ1PrIRpzhTriSv8HQbjdCpliA',
    appId: '1:647815433136:ios:9f5913c4525f0837d96475',
    messagingSenderId: '647815433136',
    projectId: 'new-vetmobile-app',
    storageBucket: 'new-vetmobile-app.firebasestorage.app',
    iosBundleId: 'com.example.newVetmobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqZIEh3kQ1PrIRpzhTriSv8HQbjdCpliA',
    appId: '1:647815433136:ios:9f5913c4525f0837d96475',
    messagingSenderId: '647815433136',
    projectId: 'new-vetmobile-app',
    storageBucket: 'new-vetmobile-app.firebasestorage.app',
    iosBundleId: 'com.example.newVetmobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClEgWa0UOlv1uLdavhvJnBDNq7z3Nmfck',
    appId: '1:647815433136:web:614c3f90dc401405d96475',
    messagingSenderId: '647815433136',
    projectId: 'new-vetmobile-app',
    authDomain: 'new-vetmobile-app.firebaseapp.com',
    storageBucket: 'new-vetmobile-app.firebasestorage.app',
  );
}
